# CGeNArate config file, created by CGeNArate web server #
[simulation]
name = 'CGeNArate web server - Circular DNA'
T0 = 298.0 # Temperature (K)
dt0 = 0.1 # timestep in picoseconds
N = 188 # Number of beads
frames = 10 # Number of frames
steps = 200 # Number of steps between frames
linear = false
seed = 1234 # random seed

[input]
file = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/str.pdb'

[output]
coordinates = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/cgenarate_traj.mdcrd'
energy = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/cgenarate_energy.csv'
plots = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/cgenarate_plots.csv'

[restore]
mode = 'print'
current = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/current.pdb'
restart = '/mnt/Web/CGN67d9bc1243337/TRAJ_CG/output_schnarp/restart.pdb'
