# CGeNArate config file, created by CGeNArate web server #
[simulation]
name = 'CGeNArate web server'
T0 = 298.0 # Temperature (K)
dt0 = 0.1 # timestep in picoseconds
N = 60 # Number of beads
frames = 100 # Number of frames
steps = 200 # Number of steps between frames
linear = true
seed = 1234 # random seed

[input]
file = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_pdb/structure_000000.pdb'

[output]
coordinates = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_schnarp/cgenarate_traj.mdcrd'
energy = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_schnarp/cgenarate_energy.csv'
plots = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_schnarp/cgenarate_plots.csv'

[restore]
mode = 'print'
current = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_schnarp/current.pdb'
restart = '/mnt/Web/CGN67d94200afbbb/TRAJ_AA/output_schnarp/restart.pdb'
