# CGeNArate config file, created by CGeNArate web server #
[simulation]
name = 'CGeNArate web server'
T0 = 298.0 # Temperature (K)
dt0 = 0.1 # timestep in picoseconds
N = 180 # Number of beads
frames = 50 # Number of frames
steps = 200 # Number of steps between frames
linear = true
seed = 1234 # random seed

[input]
file = 'input/Proteins.pdb'

[output]
coordinates = '/mnt/Web/CGN67d9bfc0515cd/TRAJ_CG/output_schnarp/cgenarate_traj.mdcrd'
energy = '/mnt/Web/CGN67d9bfc0515cd/TRAJ_CG/output_schnarp/cgenarate_energy.csv'
plots = '/mnt/Web/CGN67d9bfc0515cd/TRAJ_CG/output_schnarp/cgenarate_plots.csv'

[restore]
mode = 'none'
